Models/ErrorViewModel.cs
namespace tl2_tp6_2024_tangerinegmv.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Presupuestos.cs
namespace Tienda;
public class Presupuestos
{
    private int idPresupuesto;
    private string? nombreDestinatario;
    private string? fechaCreacion;
    private List<PresupuestosDetalle> detalle;
    public const double IVA = 0.21;

    public Presupuestos()
    {
        detalle = new List<PresupuestosDetalle>();
    }

    public string? NombreDestinatario { get => nombreDestinatario; set => nombreDestinatario = value; }
    public int IdPresupuesto {get => idPresupuesto; set => idPresupuesto = value; }
    public List<PresupuestosDetalle> Detalle { get => detalle; }
    public string? FechaCreacion { get => fechaCreacion; set => fechaCreacion = value; }

    public int MontoPresupuesto(){
        return detalle.Sum(p => p.Producto.Precio * p.Cantidad);
    }
    public double MontoPresupuestoConIva(){
         return MontoPresupuesto()*(1+IVA);
    }
    public int CantidadProductos(){
        return detalle.Sum(p => p.Cantidad);
    }
    
}

Models/PresupuestosDetalle.cs
using Tienda;

public class PresupuestosDetalle
{
   private Productos? producto;
   private int cantidad;

    public PresupuestosDetalle()
    {
    }

    public Productos? Producto { get => producto; set => producto=value;}
    public int Cantidad { get => cantidad; set => cantidad = value; }

    public void CargarProducto( Productos prod)
    {
        producto = prod;
    }
}

Models/Productos.cs
namespace Tienda
{
    public class Productos
    {
        private int idProducto;
        private string? descripcion;
        private int precio;

        public Productos()
        {
        }

      
        public string? Descripcion { get => descripcion; set => descripcion = value; }
        public int Precio { get => precio; set => precio = value; }
        public int IdProducto { get => idProducto; set => idProducto = value; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp6_2024_tangerinegmv.Models;

namespace tl2_tp6_2024_tangerinegmv.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/PresupuestosController.cs
using SQLitePCL;
using Tienda;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tl2_tp6_2024_tangerinegmv.Controllers;

public class PresupuestosController : Controller
{
     private readonly ILogger<HomeController> _logger;
    private PresupuestosRepository presRep = new PresupuestosRepository();

     public PresupuestosController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

     public IActionResult Index()
    {
        return View(presRep.ListarPresupuestos());
    }
}

Controllers/ProductosController.cs
using SQLitePCL;
using Tienda;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tl2_tp6_2024_tangerinegmv.Controllers;





public class ProductosController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private ProductosRepository prodRep = new ProductosRepository();

     public ProductosController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }


    public IActionResult Index()
    {
        return View(prodRep.ListarProductos());
    }

    [HttpGet]
    public IActionResult CrearProducto()
    {
        return View(new Productos());
    }

    [HttpPost]
    public IActionResult CrearProducto(Productos producto)
    {
        prodRep.CrearNuevo(producto);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult ModificarProducto(int id)
    {
        return View(prodRep.DetallesProducto(id));
    }
    [HttpPost]
    public IActionResult ModificarProducto(int id, Productos prod)
    {
      prodRep.ModificarProducto(id, prod);
      return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult BorrarProducto(int id)
    {
      
      return View(prodRep.DetallesProducto(id));
    }

 
    public IActionResult ConfirmarEliminacion(int id)
    {
        prodRep.BorrarProducto(id);
        return RedirectToAction("Index");
    }


}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Presupuestos/Index.cshtml
@{
    ViewData["Title"] = "Presupuestos";
}


@model List<Tienda.Presupuestos> 

<div class="text-center">
    <h1 class="display-4">Listado de presupuesto</h1>
</div>
<table class="table table-primary table-striped">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre destinatario</th>
      <th scope="col">Fecha de creación</th>
      <th scope="col">Monto total</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    
    @foreach(var presupuesto in Model)
    {
        <tr>
            <th scope="row">@presupuesto.IdPresupuesto</th>
            <td>@presupuesto.NombreDestinatario</td>
            <td>@presupuesto.FechaCreacion</td>
            <td>$@presupuesto.MontoPresupuestoConIva()</td>
            <td><button type="button" class="btn btn-primary"><a class="nav-link text-light" asp-area="" asp-controller="Presupuestos" asp-action="ModificarPresupuesto" asp-route-id="@presupuesto.IdPresupuesto">Modificar</a></button></td>
            <td><button type="button" class="btn btn-danger"><a class="nav-link text-light" asp-area="" asp-controller="Presupuestos" asp-action="EliminarPresupuesto" asp-route-id="@presupuesto.IdPresupuesto">Eliminar</a></button></td>
            <td><button type="button" class="btn btn-info"><a class="nav-link text-light" asp-area="" asp-controller="Presupuestos" asp-action="MostrarPresupuestoDetalle" asp-route-id="@presupuesto.IdPresupuesto">Detalle</a></button></td>
            <td><button type="button" class="btn btn-success"><a class="nav-link text-light" asp-area="" asp-controller="Presupuestos" asp-action="AgregarProducto" asp-route-id="@presupuesto.IdPresupuesto">Agregar Producto</a></button></td>
        </tr>
    }
  </tbody>
</table>
<div class="text-center">
    <button type="button" class="btn btn-success"><a   class="nav-link text-light" asp-area="" asp-controller="Presupuestos" asp-action="CrearPresupuesto">Agregar presupuesto a la lista</a></button>
</div>

Views/Productos/BorrarProducto.cshtml
@{
  ViewData["Title"] = "BorrarProducto";
  
}

@model Tienda.Productos

<div class="text-center">
  <h2>¿Seguro que desea eliminar el siguiente producto?</h2>
</div>
<table class="table table-danger table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">@Model.IdProducto</th>
      <td>@Model.Descripcion</td>
      <td>@Model.Precio</td>
    </tr>
  </tbody>
</table>

<button type="button" class="btn btn-success"><a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="ConfirmarEliminacion" asp-route-id="@Model.IdProducto" >Confirmar</a></button> @*Se pude utilizar solo uno?*@
<button type="button" class="btn btn-danger"><a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="Index">Denegar</a></button>

Views/Productos/CrearProducto.cshtml
@{
    ViewData["Title"] = "CrearProducto";
}

@model Tienda.Productos

<form asp-controller="Productos" asp-action="CrearProducto">
  <div class="mb-3">
    <label asp-for=@Model.Descripcion class="form-label">Descipcion</label>
    <input asp-for=@Model.Descripcion type="text" class="form-control">
    <label asp-for=@Model.Precio class="form-label">Precio</label>
    <input asp-for=@Model.Precio type="number" class="form-control">
  </div>    
  <button type="submit" class="btn btn-outline-success">Crear</button>
</form>

Views/Productos/Index.cshtml
@{
    ViewData["Title"] = "Productos";
}


@model List<Tienda.Productos> 

<div class="text-center">
    <h1 class="display-4">Listado de productos</h1>
</div>
<table class="table table-primary table-striped">
    <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach(var producto in Model)
    {
        <tr>
            <th scope="row">@producto.IdProducto</th>
            <td>@producto.Descripcion</td>
            <td>@producto.Precio</td>
            <td><button type="button" class="btn btn-primary"><a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="ModificarProducto" asp-route-id="@producto.IdProducto">Modificar</a></button></td>
            <td><button type="button" class="btn btn-danger"><a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="BorrarProducto" asp-route-id="@producto.IdProducto">Eliminar</a></button></td>
        </tr>
    }
  </tbody>
</table>
<div class="text-center">
    <button type="button" class="btn btn-success"><a   class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="CrearProducto">Agregar producto a la lista</a></button>
</div>

Views/Productos/ModificarProducto.cshtml
@{
    ViewData["Title"] = "ModificarProducto";
}

@model Tienda.Productos

<form asp-controller="Productos" asp-action="ModificarProducto">
  <div class="mb-3">
    <label asp-for=@Model.Descripcion class="form-label">Descipcion</label>
    <input asp-for=@Model.Descripcion type="text" class="form-control">
    <label asp-for=@Model.Precio class="form-label">Precio</label>
    <input asp-for=@Model.Precio type="number" class="form-control">
  </div>    
  <button type="submit" class="btn btn-outline-success">Modificar</button>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tl2_tp6_2024_tangerinegmv</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp6_2024_tangerinegmv.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tl2_tp6_2024_tangerinegmv</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presupuestos" asp-action="Index">Presupuestos</a>
                        </li> 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - tl2_tp6_2024_tangerinegmv - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>